spring.application.name=springproject

# Configurar el puerto 8081 para evitar el conflicto con el puerto 8080 que tenías antes
server.port=8081

# Para que Hibernate cree o actualice las tablas automáticamente a medida que creas clases de modelo (Entities)
spring.jpa.hibernate.ddl-auto=update

# ==== Configuración de Base de Datos (PostgreSQL que acabamos de instalar) ====
spring.datasource.url=jdbc:postgresql://localhost:5432/springproject
# Por defecto en Mac Homebrew, el usuario es tu nombre de sistema (pablonietohurtado) sin contraseña.
spring.datasource.username=pablonietohurtado
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver